import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { AppSettings, PromptSettings, ExportSettings } from '../types';

interface SettingsState extends AppSettings {
    // Legacy/Core State
    prompts: PromptSettings;
    exportInfo: ExportSettings;

    setTone: (tone: AppSettings['analysisTone']) => void;
    setStyle: (style: AppSettings['analysisStyle']) => void;
    setDepth: (depth: AppSettings['analysisDepth']) => void;
    setFormat: (format: AppSettings['outputFormat']) => void;
    setLayout: (layout: AppSettings['layoutMode']) => void;
    setInstructions: (text: string) => void;
    setTheme: (theme: AppSettings['theme']) => void;

    // Legacy/Core Actions
    setPrompts: (prompts: PromptSettings) => void;
    setExportInfo: (info: ExportSettings) => void;

    resetDefaults: () => void;
}

export const useSettingsStore = create<SettingsState>()(
    persist(
        (set) => ({
            // Default Values for New Features
            analysisTone: 'analytical',
            analysisStyle: 'step-by-step',
            analysisDepth: 'medium',
            outputFormat: 'markdown',
            layoutMode: 'single',
            customInstructions: '',
            theme: 'dark',

            // Default Values for Core Features
            prompts: {
                systemPrompt: "You are an expert technical writer. Analyze the screenshot and provide a step-by-step description.",
                userPrompt: "Describe the action taking place in this screenshot. Focus on the UI elements and interactions.",
                polishPrompt: "Rewrite the following text to be professional, concise, and grammatically correct."
            },
            exportInfo: {
                headerColor: '#0ea5e9',
                fontFamily: 'Inter',
                footerText: 'Generated by Screenshot Analyzer AI',
                showLogo: true,
                logoUrl: ''
            },

            setTone: (tone) => set({ analysisTone: tone }),
            setStyle: (style) => set({ analysisStyle: style }),
            setDepth: (depth) => set({ analysisDepth: depth }),
            setFormat: (format) => set({ outputFormat: format }),
            setLayout: (layout) => set({ layoutMode: layout }),
            setInstructions: (text) => set({ customInstructions: text }),
            setTheme: (theme) => set({ theme }),

            setPrompts: (prompts) => set({ prompts }),
            setExportInfo: (info) => set({ exportInfo: info }),

            resetDefaults: () => set({
                analysisTone: 'analytical',
                analysisStyle: 'step-by-step',
                analysisDepth: 'medium',
                outputFormat: 'markdown',
                layoutMode: 'single',
                customInstructions: ''
            })
        }),
        {
            name: 'screenshot-analyzer-settings',
        }
    )
);
