import React, { useState, useEffect } from 'react';
import { X, Save, RotateCcw, LayoutTemplate, Sparkles, Palette, Type, Image as ImageIcon } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface Settings {
    prompts: {
        systemPrompt: string;
        userPrompt: string;
        polishPrompt: string;
    };
    exportInfo: {
        headerColor: string;
        fontFamily: string;
        footerText: string;
        showLogo: boolean;
        logoUrl: string;
    };
}

interface SettingsModalProps {
    isOpen: boolean;
    onClose: () => void;
    settings: Settings;
    onSave: (settings: Settings) => void;
}

const SettingsModal: React.FC<SettingsModalProps> = ({ isOpen, onClose, settings, onSave }) => {
    const [activeTab, setActiveTab] = useState<'prompts' | 'export'>('prompts');
    const [localSettings, setLocalSettings] = useState<Settings>(settings);

    // Sync when settings prop changes or modal opens
    useEffect(() => {
        if (isOpen) {
            setLocalSettings(settings);
        }
    }, [isOpen, settings]);

    const handleChange = (section: keyof Settings, key: string, value: string) => {
        setLocalSettings(prev => ({
            ...prev,
            [section]: {
                ...prev[section],
                [key]: value
            }
        }));
    };

    const handleSave = () => {
        onSave(localSettings);
        onClose();
    };

    const handleReset = () => {
        const defaultSettings: Settings = {
            prompts: {
                systemPrompt: "You are an expert technical writer. Analyze the screenshot and provide a step-by-step description.",
                userPrompt: "Describe the action taking place in this screenshot. Focus on the UI elements and interactions.",
                polishPrompt: "Rewrite the following text to be professional, concise, and grammatically correct."
            },
            exportInfo: {
                headerColor: '#3b82f6', // blue-500
                fontFamily: 'Inter',
                footerText: 'Generated by Screenshot Analyzer AI',
                showLogo: true,
                logoUrl: '' // Empty means default or none
            }
        };
        setLocalSettings(defaultSettings);
    };

    const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = (e) => {
                if (e.target?.result as string) {
                    handleChange('exportInfo', 'logoUrl', e.target!.result as string);
                }
            };
            reader.readAsDataURL(file);
        }
    };

    if (!isOpen) return null;

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="bg-slate-900 border border-slate-700 w-full max-w-4xl max-h-[90vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col"
                >
                    {/* Header */}
                    <div className="flex items-center justify-between p-6 border-b border-slate-700 bg-slate-800/50">
                        <div className="flex items-center gap-3">
                            <div className="p-2 bg-primary-500/20 rounded-lg">
                                <LayoutTemplate className="w-6 h-6 text-primary-400" />
                            </div>
                            <h2 className="text-xl font-bold text-white">Settings & Customization</h2>
                        </div>
                        <button onClick={onClose} className="p-2 text-slate-400 hover:text-white rounded-lg hover:bg-slate-700 transition-colors">
                            <X className="w-6 h-6" />
                        </button>
                    </div>

                    {/* Body */}
                    <div className="flex flex-1 overflow-hidden">
                        {/* Sidebar */}
                        <div className="w-64 bg-slate-900 border-r border-slate-700 p-4 space-y-2">
                            <button
                                onClick={() => setActiveTab('prompts')}
                                className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${activeTab === 'prompts'
                                    ? 'bg-primary-600 text-white shadow-lg shadow-primary-500/20'
                                    : 'text-slate-400 hover:bg-slate-800 hover:text-white'
                                    }`}
                            >
                                <Sparkles className="w-5 h-5" />
                                <span className="font-medium">AI Prompts</span>
                            </button>
                            <button
                                onClick={() => setActiveTab('export')}
                                className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${activeTab === 'export'
                                    ? 'bg-primary-600 text-white shadow-lg shadow-primary-500/20'
                                    : 'text-slate-400 hover:bg-slate-800 hover:text-white'
                                    }`}
                            >
                                <Palette className="w-5 h-5" />
                                <span className="font-medium">Export Styling</span>
                            </button>
                        </div>

                        {/* Content Area */}
                        <div className="flex-1 p-6 overflow-y-auto bg-slate-900/50">

                            {/* --- Prompts Tab --- */}
                            {activeTab === 'prompts' && (
                                <div className="space-y-6 animate-fadeIn">
                                    <div className="space-y-4">
                                        <div>
                                            <label className="block text-sm font-medium text-slate-300 mb-2">System Role</label>
                                            <p className="text-xs text-slate-500 mb-2">Defines the overall persona of the AI.</p>
                                            <textarea
                                                className="w-full bg-slate-800 border border-slate-700 rounded-xl p-4 text-slate-200 focus:ring-2 focus:ring-primary-500 outline-none h-24 resize-none"
                                                value={localSettings.prompts?.systemPrompt || ''}
                                                onChange={(e) => handleChange('prompts', 'systemPrompt', e.target.value)}
                                            />
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-slate-300 mb-2">Analysis Instruction</label>
                                            <p className="text-xs text-slate-500 mb-2">The specific instruction sent with each screenshot.</p>
                                            <textarea
                                                className="w-full bg-slate-800 border border-slate-700 rounded-xl p-4 text-slate-200 focus:ring-2 focus:ring-primary-500 outline-none h-24 resize-none"
                                                value={localSettings.prompts?.userPrompt || ''}
                                                onChange={(e) => handleChange('prompts', 'userPrompt', e.target.value)}
                                            />
                                        </div>

                                        <div>
                                            <label className="block text-sm font-medium text-slate-300 mb-2">"Make Professional" Prompt</label>
                                            <p className="text-xs text-slate-500 mb-2">Used when polishing text.</p>
                                            <textarea
                                                className="w-full bg-slate-800 border border-slate-700 rounded-xl p-4 text-slate-200 focus:ring-2 focus:ring-primary-500 outline-none h-24 resize-none"
                                                value={localSettings.prompts?.polishPrompt || ''}
                                                onChange={(e) => handleChange('prompts', 'polishPrompt', e.target.value)}
                                            />
                                        </div>
                                    </div>
                                </div>
                            )}

                            {/* --- Export Tab --- */}
                            {activeTab === 'export' && (
                                <div className="space-y-8 animate-fadeIn">
                                    {/* Branding Section */}
                                    <div className="space-y-4">
                                        <h3 className="text-lg font-semibold text-white border-b border-slate-700 pb-2">Branding</h3>

                                        <div className="flex gap-6">
                                            <div className="flex-1">
                                                <label className="block text-sm font-medium text-slate-300 mb-2">Custom Logo</label>
                                                <div className="flex items-center gap-4">
                                                    <div className="w-16 h-16 bg-slate-800 rounded-lg border border-slate-700 flex items-center justify-center overflow-hidden">
                                                        {localSettings.exportInfo?.logoUrl ? (
                                                            <img src={localSettings.exportInfo.logoUrl} alt="Logo" className="w-full h-full object-contain" />
                                                        ) : (
                                                            <ImageIcon className="w-8 h-8 text-slate-600" />
                                                        )}
                                                    </div>
                                                    <div>
                                                        <label className="cursor-pointer bg-slate-700 hover:bg-slate-600 text-white px-4 py-2 rounded-lg text-sm transition-colors inline-block">
                                                            Upload Logo
                                                            <input type="file" accept="image/*" className="hidden" onChange={handleLogoUpload} />
                                                        </label>
                                                        <br />
                                                        {localSettings.exportInfo?.logoUrl && (
                                                            <button
                                                                onClick={() => handleChange('exportInfo', 'logoUrl', '')}
                                                                className="text-xs text-red-400 hover:underline mt-2"
                                                            >
                                                                Remove Logo
                                                            </button>
                                                        )}
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="flex-1">
                                                <label className="block text-sm font-medium text-slate-300 mb-2">Footer Text</label>
                                                <input
                                                    type="text"
                                                    className="w-full bg-slate-800 border border-slate-700 rounded-lg p-2.5 text-slate-200 focus:ring-2 focus:ring-primary-500 outline-none"
                                                    value={localSettings.exportInfo?.footerText || ''}
                                                    onChange={(e) => handleChange('exportInfo', 'footerText', e.target.value)}
                                                    placeholder="e.g. Confidential - Internal Use Only"
                                                />
                                            </div>
                                        </div>
                                    </div>

                                    {/* Styling Section */}
                                    <div className="space-y-4">
                                        <h3 className="text-lg font-semibold text-white border-b border-slate-700 pb-2">Styling</h3>

                                        <div className="grid grid-cols-2 gap-6">
                                            <div>
                                                <label className="block text-sm font-medium text-slate-300 mb-2 flex items-center gap-2">
                                                    <Palette className="w-4 h-4" /> Header Color
                                                </label>
                                                <div className="flex gap-2">
                                                    <input
                                                        type="color"
                                                        value={localSettings.exportInfo?.headerColor || '#3b82f6'}
                                                        onChange={(e) => handleChange('exportInfo', 'headerColor', e.target.value)}
                                                        className="w-10 h-10 rounded-lg cursor-pointer bg-transparent border-none"
                                                    />
                                                    <input
                                                        type="text"
                                                        value={localSettings.exportInfo?.headerColor || '#3b82f6'}
                                                        onChange={(e) => handleChange('exportInfo', 'headerColor', e.target.value)}
                                                        className="flex-1 bg-slate-800 border border-slate-700 rounded-lg p-2 text-slate-200 font-mono text-sm"
                                                    />
                                                </div>
                                            </div>

                                            <div>
                                                <label className="block text-sm font-medium text-slate-300 mb-2 flex items-center gap-2">
                                                    <Type className="w-4 h-4" /> Font Family (PDF)
                                                </label>
                                                <select
                                                    className="w-full bg-slate-800 border border-slate-700 rounded-lg p-2.5 text-slate-200 outline-none"
                                                    value={localSettings.exportInfo?.fontFamily || 'Inter'}
                                                    onChange={(e) => handleChange('exportInfo', 'fontFamily', e.target.value)}
                                                >
                                                    <option value="Inter">Inter (Sans-serif)</option>
                                                    <option value="Times">Times New Roman (Serif)</option>
                                                    <option value="Courier">Courier (Monospace)</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}

                        </div>
                    </div>

                    {/* Footer */}
                    <div className="p-6 border-t border-slate-700 bg-slate-800/50 flex justify-between items-center">
                        <button
                            onClick={handleReset}
                            className="text-slate-400 hover:text-white flex items-center gap-2 text-sm transition-colors"
                        >
                            <RotateCcw className="w-4 h-4" /> Reset Defaults
                        </button>
                        <div className="flex gap-3">
                            <button
                                onClick={onClose}
                                className="px-6 py-2.5 rounded-xl text-slate-300 hover:bg-slate-700 transition-colors font-medium"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={handleSave}
                                className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-primary-600 to-primary-500 hover:from-primary-500 hover:to-primary-400 text-white font-medium shadow-lg shadow-primary-500/20 flex items-center gap-2 transition-all"
                            >
                                <Save className="w-4 h-4" /> Save Changes
                            </button>
                        </div>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
};

export default SettingsModal;
